//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intelincApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Number { get; set; }
        public string Date { get; set; }
        public string Count { get; set; }
        public Nullable<int> ItemID { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
